# Generated by Django 5.2.1 on 2025-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
