# Generated by Django 5.2.1 on 2025-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField()),
                ("review_text", models.TextField()),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
