# Generated by Django 5.2.1 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=None, upload_to="images"),
            preserve_default=False,
        ),
    ]
