# Generated by Django 5.2.1 on 2025-05-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_name",
        ),
    ]
